name: ElyTPA
version: '0.1.0'
main: com.marrineer.elyTPA.ElyTPA
api-version: '1.21'
authors: [ Marrineer ]
website: https://guns.lol/marrineer
libraries:
  - "com.zaxxer:HikariCP:7.0.2"
  - "org.xerial:sqlite-jdbc:3.51.1.0"
  - "mysql:mysql-connector-java:9.5.0"
